"""AI generation layer.

If `GEMINI_API_KEY` is configured (Google AI Studio), quizzes/flashcards are
generated by calling the Gemini API's OpenAI-compatible Chat Completions
endpoint with a strict JSON-output prompt.

If no key is configured, a deterministic, fully-offline heuristic generator
is used instead so the whole product still works end-to-end (useful for
local dev, demos, and grading environments without external API access).
"""
import json
import random
import re
from typing import List, Dict

import httpx

from app.config import settings
from app.services.pdf_service import split_into_sentences, identify_key_terms

random.seed()


# ===========================================================================
# Public entry points
# ===========================================================================
def generate_quiz(text: str, subject: str, question_count: int, difficulty: str,
                   question_types: List[str]) -> List[Dict]:
    import logging
    if settings.GEMINI_API_KEY:
        try:
            questions = _generate_quiz_gemini(text, subject, question_count, difficulty, question_types)
            if questions:
                if len(questions) < question_count:
                    logging.warning(
                        "Gemini returned only %d/%d valid questions; padding from offline generator",
                        len(questions), question_count,
                    )
                    existing = {q["question_text"].lower() for q in questions}
                    for q in _generate_quiz_offline(text, subject, question_count * 2, difficulty, question_types):
                        if len(questions) >= question_count:
                            break
                        if q["question_text"].lower() not in existing:
                            questions.append(q)
                            existing.add(q["question_text"].lower())
                return questions
            logging.warning("Gemini returned no valid questions; using offline generator")
        except Exception as e:
            logging.exception("Gemini quiz generation failed, falling back to offline generator")
    return _generate_quiz_offline(text, subject, question_count, difficulty, question_types)

def generate_flashcards(text: str, subject: str, count: int) -> List[Dict]:
    import logging
    if settings.GEMINI_API_KEY:
        try:
            flashcards = _generate_flashcards_gemini(text, subject, count)
            if flashcards:
                if len(flashcards) < count:
                    logging.warning(
                        "Gemini returned only %d/%d valid flashcards; padding from offline generator",
                        len(flashcards), count,
                    )
                    existing = {fc["front"].lower() for fc in flashcards}
                    for fc in _generate_flashcards_offline(text, subject, count * 2):
                        if len(flashcards) >= count:
                            break
                        if fc["front"].lower() not in existing:
                            flashcards.append(fc)
                            existing.add(fc["front"].lower())
                return flashcards
            logging.warning("Gemini returned no valid flashcards; using offline generator")
        except Exception as e:
            logging.exception("Gemini flashcard generation failed, falling back to offline generator")
    return _generate_flashcards_offline(text, subject, count)

# ===========================================================================
# Gemini (Google AI Studio) generation
# ===========================================================================
_QUIZ_SYSTEM_PROMPT = """You are an expert exam writer for first-year BSCS/BSIT college students.
You write challenging, unambiguous questions that test real understanding of the source material.
Rules you must always follow:
- Output ONLY a valid JSON object. No markdown fences, no commentary.
- Use EXACTLY the question types requested, and distribute them evenly across the requested count.
- Multiple Choice: exactly 4 distinct, plausible choices (similar length/granularity), one clearly correct.
  Distractors must be realistic misconceptions or nearby concepts from the material — never filler text
  like "None of the above", "Option 2", or "All of the above" unless genuinely correct.
  The correct answer must appear verbatim as one of the choices.
- True or False: statements must be clearly verifiable from the text; avoid negation tricks or vagueness.
  choices must be exactly ["True", "False"].
- Identification: the answer must be 1-3 words, taken directly from the source text, and unambiguous.
- Never reveal the answer inside the question text. Never number the questions.
- Produce EXACTLY as many questions as requested. If the source text is long enough, each question
  should cover a DIFFERENT part of the material (no near-duplicates)."""

_FLASHCARD_SYSTEM_PROMPT = """You are an expert study-guide writer for first-year BSCS/BSIT college students.
You write concise, high-quality flashcards that test real recall of the source material.
Rules you must always follow:
- Output ONLY a valid JSON object. No markdown fences, no commentary.
- front: a specific question or term prompt (never just "What is X?" every time — vary the phrasing:
  "Define...", "What is the difference between X and Y?", "Why does...?", "When is...?").
- back: a clear, self-contained explanation in 1-3 sentences, faithful to the source text.
- Each card covers a DIFFERENT key concept. Produce EXACTLY as many flashcards as requested."""


def _extract_json(content: str) -> Dict:
    """Parse the model's response as JSON, tolerating markdown fences or stray text."""
    content = content.strip()
    # strip ```json ... ``` fences if present
    fence = re.search(r"```(?:json)?\s*(.*?)\s*```", content, re.DOTALL)
    if fence:
        content = fence.group(1)
    try:
        return json.loads(content)
    except json.JSONDecodeError:
        # last resort: grab the outermost {...} block
        match = re.search(r"\{.*\}", content, re.DOTALL)
        if match:
            return json.loads(match.group(0))
        raise


def _norm(value) -> str:
    return str(value).strip()


def _validate_questions(raw: List[Dict], question_types: List[str]) -> List[Dict]:
    """Keep only well-formed, self-consistent questions; normalize their shape."""
    allowed = {t.strip().lower(): t for t in (question_types or [])}
    cleaned, seen = [], set()
    for q in raw:
        if not isinstance(q, dict):
            continue
        qtype_raw = _norm(q.get("question_type", "")).lower()
        qtype = allowed.get(qtype_raw)
        if not qtype:
            continue
        text = _norm(q.get("question_text", ""))
        answer = _norm(q.get("correct_answer", ""))
        if not text or not answer:
            continue
        if qtype == "Identification":
            choices = None
        else:
            choices = [_norm(c) for c in (q.get("choices") or []) if _norm(c)]
            if qtype == "True or False":
                choices = ["True", "False"]
                match = next((c for c in choices if c.lower() == answer.lower()), None)
                if not match:
                    continue
                answer = match
            else:  # Multiple Choice
                if len(choices) < 2 or answer not in choices:
                    continue
                seen_c, unique = set(), []
                for c in choices:
                    if c.lower() not in seen_c:
                        seen_c.add(c.lower())
                        unique.append(c)
                if answer not in unique:
                    continue
                choices = unique
        key = text.lower()
        if key in seen:
            continue
        seen.add(key)
        cleaned.append({
            "question_type": qtype,
            "question_text": text[:500],
            "choices": choices,
            "correct_answer": answer,
        })
    return cleaned


def _validate_flashcards(raw: List[Dict], count: int) -> List[Dict]:
    cleaned, seen = [], set()
    for fc in raw:
        if not isinstance(fc, dict):
            continue
        front = _norm(fc.get("front", ""))
        back = _norm(fc.get("back", ""))
        if not front or not back or len(back) < 10:
            continue
        key = front.lower()
        if key in seen:
            continue
        seen.add(key)
        cleaned.append({"front": front[:300], "back": back[:1000]})
        if len(cleaned) >= count:
            break
    return cleaned


_GEMINI_FALLBACK_MODELS = [
    None,  # the configured model first
    "gemini-flash-latest",
    "gemini-3-flash-preview",
    "gemini-2.5-flash-lite",
]


def _call_gemini(system_prompt: str, user_prompt: str, max_tokens: int = 8192) -> str:
    import logging
    import time

    last_error = None
    for fallback_model in _GEMINI_FALLBACK_MODELS:
        model = fallback_model or settings.GEMINI_MODEL
        for attempt in range(3):  # retry transient failures (429/500/503)
            try:
                resp = httpx.post(
                    f"{settings.GEMINI_BASE_URL}/chat/completions",
                    headers={"Authorization": f"Bearer {settings.GEMINI_API_KEY}", "Content-Type": "application/json"},
                    json={
                        "model": model,
                        "messages": [
                            {"role": "system", "content": system_prompt},
                            {"role": "user", "content": user_prompt},
                        ],
                        "temperature": 0.6,
                        "max_tokens": max_tokens,
                        "response_format": {"type": "json_object"},
                    },
                    timeout=120,
                )
                # 404 -> model gone/unavailable to this key: try the next model immediately
                if resp.status_code == 404:
                    logging.warning("Gemini model %s unavailable (404), trying next model", model)
                    last_error = httpx.HTTPStatusError(f"404 for model {model}", request=resp.request, response=resp)
                    break
                resp.raise_for_status()
                data = resp.json()
                content = (data.get("choices") or [{}])[0].get("message", {}).get("content", "")
                if not content:
                    raise ValueError("Gemini returned an empty response")
                return content
            except (httpx.HTTPStatusError, httpx.TransportError, ValueError) as e:
                last_error = e
                status = getattr(getattr(e, "response", None), "status_code", None)
                # 400/401/403 are permanent (bad key/request) — don't retry
                if status in (400, 401, 403):
                    raise
                time.sleep(2 * (attempt + 1))  # back off: 2s, 4s
        # exhausted retries on this model -> try the next fallback model
    raise last_error if last_error else RuntimeError("Gemini call failed on all models")


def _generate_quiz_gemini(text: str, subject: str, question_count: int, difficulty: str,
                           question_types: List[str]) -> List[Dict]:
    types_list = [t for t in question_types if t] or ["Multiple Choice"]
    excerpt = text[:24000]  # generous, but keeps the prompt bounded
    difficulty_hint = (
        "straightforward recall of definitions and basic facts" if difficulty == "Easy"
        else "requires connecting two or more ideas from the text, application, or careful "
             "distinction between similar concepts" if difficulty == "Hard"
        else "a mix of recall and light application"
    )
    user_prompt = f"""
Create a {difficulty.lower()} quiz on "{subject}" for first-year college students.

Source module text (your ONLY source of truth — do not invent facts not supported by it):
\"\"\"{excerpt}\"\"\"

Requirements:
- Generate exactly {question_count} questions, cycling through these types: {', '.join(types_list)}.
- Difficulty "{difficulty}": {difficulty_hint}.
- Spread the questions across the whole excerpt; do not cluster them on the first few paragraphs.
- Each question must be answerable purely from the text above.

Return ONLY JSON of the form:
{{"questions": [
  {{"question_type": "Multiple Choice", "question_text": "...", "choices": ["...","...","...","..."], "correct_answer": "..."}},
  {{"question_type": "True or False", "question_text": "...", "choices": ["True","False"], "correct_answer": "True"}},
  {{"question_type": "Identification", "question_text": "...", "choices": null, "correct_answer": "..."}}
]}}
correct_answer must exactly match one of the choices (or be the short identification answer)."""
    content = _call_gemini(_QUIZ_SYSTEM_PROMPT, user_prompt)
    parsed = _extract_json(content)
    questions = _validate_questions(parsed.get("questions", []), types_list)[:question_count]

    # Top-up pass: ask Gemini for the missing questions only
    if 0 < len(questions) < question_count:
        missing = question_count - len(questions)
        retry_prompt = f"""
Earlier you created {len(questions)} questions from the module text below, but {missing} more are needed.
Create exactly {missing} ADDITIONAL questions of these types: {', '.join(types_list)}.
Do NOT repeat or rephrase any of these already-used questions — cover DIFFERENT parts of the text:
{' | '.join(q['question_text'][:80] for q in questions)}

Source module text:
\"\"\"{excerpt}\"\"\"

Return ONLY JSON: {{"questions": [...]}}
"""
        try:
            content = _call_gemini(_QUIZ_SYSTEM_PROMPT, retry_prompt)
            more = _validate_questions(_extract_json(content).get("questions", []), types_list)
            existing_texts = {q["question_text"].lower() for q in questions}
            for q in more:
                if len(questions) >= question_count:
                    break
                if q["question_text"].lower() not in existing_texts:
                    questions.append(q)
                    existing_texts.add(q["question_text"].lower())
        except Exception:
            import logging
            logging.warning("Gemini top-up call failed; padding quiz from offline generator")
    return questions


def _generate_flashcards_gemini(text: str, subject: str, count: int) -> List[Dict]:
    excerpt = text[:24000]
    user_prompt = f"""
Create {count} study flashcards on "{subject}" for first-year college students.

Source module text (your ONLY source of truth — do not invent facts not supported by it):
\"\"\"{excerpt}\"\"\"

Requirements:
- Cover the {count} most important/central concepts, spread across the whole excerpt.
- Each card must be self-contained: understandable without seeing the source text.
- Do NOT create near-duplicate cards.

Return ONLY JSON of the form:
{{"flashcards": [{{"front": "A short question or term", "back": "A clear definition/explanation"}}]}}"""
    content = _call_gemini(_FLASHCARD_SYSTEM_PROMPT, user_prompt)
    parsed = _extract_json(content)
    flashcards = _validate_flashcards(parsed.get("flashcards", []), count)

    if 0 < len(flashcards) < count:
        missing = count - len(flashcards)
        retry_prompt = f"""
Create exactly {missing} ADDITIONAL flashcards on "{subject}" from the text below.
Do NOT repeat the concepts already covered:
{' | '.join(fc['front'][:60] for fc in flashcards)}

Source module text:
\"\"\"{excerpt}\"\"\"

Return ONLY JSON: {{"flashcards": [...]}}
"""
        try:
            content = _call_gemini(_FLASHCARD_SYSTEM_PROMPT, retry_prompt)
            more = _validate_flashcards(_extract_json(content).get("flashcards", []), missing)
            existing = {fc["front"].lower() for fc in flashcards}
            for fc in more:
                if len(flashcards) >= count:
                    break
                if fc["front"].lower() not in existing:
                    flashcards.append(fc)
                    existing.add(fc["front"].lower())
        except Exception:
            import logging
            logging.warning("Gemini top-up call failed; padding flashcards from offline generator")
    return flashcards


# ===========================================================================
# Offline heuristic fallback (no external API required)
# ===========================================================================
_DIFFICULTY_SENTENCE_LEN = {
    "Easy": (25, 90),
    "Medium": (40, 140),
    "Hard": (60, 220),
    "Mixed": (25, 220),
}


def _pick_sentences(text: str, difficulty: str, n: int) -> List[str]:
    sentences = split_into_sentences(text)
    lo, hi = _DIFFICULTY_SENTENCE_LEN.get(difficulty, (25, 200))
    filtered = [s for s in sentences if lo <= len(s) <= hi]
    pool = filtered if len(filtered) >= n else sentences
    if not pool:
        pool = ["This module covers foundational concepts for the course."]
    random.shuffle(pool)
    # cycle through if not enough unique sentences
    out = []
    i = 0
    while len(out) < n:
        out.append(pool[i % len(pool)])
        i += 1
    return out


def _keyword_from_sentence(sentence: str, key_terms: List[str]) -> str:
    for term in key_terms:
        if re.search(r"\b" + re.escape(term) + r"\b", sentence, re.IGNORECASE):
            return term
    words = [w for w in re.findall(r"[A-Za-z]{5,}", sentence)]
    return words[0].lower() if words else "concept"


def _generate_quiz_offline(text: str, subject: str, question_count: int, difficulty: str,
                            question_types: List[str]) -> List[Dict]:
    key_terms = identify_key_terms(text) or [subject]
    sentences = _pick_sentences(text, difficulty, question_count)
    questions = []
    types_cycle = question_types if question_types else ["Multiple Choice"]

    for i in range(question_count):
        sentence = sentences[i]
        term = _keyword_from_sentence(sentence, key_terms)
        qtype = types_cycle[i % len(types_cycle)]

        if qtype == "True or False":
            is_true = random.random() > 0.5
            statement = sentence if is_true else _negate(sentence)
            questions.append({
                "question_type": "True or False",
                "question_text": f"True or False: {statement}",
                "choices": ["True", "False"],
                "correct_answer": "True" if is_true else "False",
            })
        elif qtype == "Identification":
            questions.append({
                "question_type": "Identification",
                "question_text": f"Based on the module, what key term relates to: \"{_blank_out(sentence, term)}\"?",
                "choices": None,
                "correct_answer": term,
            })
        else:  # Multiple Choice
            distractors = [t for t in key_terms if t != term][:3]
            while len(distractors) < 3:
                distractors.append(f"{term}-related concept {len(distractors)+1}")
            choices = distractors + [term]
            random.shuffle(choices)
            questions.append({
                "question_type": "Multiple Choice",
                "question_text": f"Which term best completes this statement from the module?\n\"{_blank_out(sentence, term)}\"",
                "choices": choices,
                "correct_answer": term,
            })
    return questions


def _blank_out(sentence: str, term: str) -> str:
    pattern = re.compile(re.escape(term), re.IGNORECASE)
    blanked = pattern.sub("____", sentence, count=1)
    if blanked == sentence:
        blanked = sentence + " (____)"
    return blanked[:280]


def _negate(sentence: str) -> str:
    replacements = [
        (r"\bis\b", "is not"), (r"\bare\b", "are not"),
        (r"\bcan\b", "cannot"), (r"\bwill\b", "will not"),
        (r"\bdoes\b", "does not"), (r"\bhas\b", "does not have"),
    ]
    for pattern, repl in replacements:
        if re.search(pattern, sentence, re.IGNORECASE):
            return re.sub(pattern, repl, sentence, count=1, flags=re.IGNORECASE)
    return "It is not true that " + sentence[0].lower() + sentence[1:]


def _generate_flashcards_offline(text: str, subject: str, count: int) -> List[Dict]:
    key_terms = identify_key_terms(text, max_terms=count * 2) or [subject]
    sentences = split_into_sentences(text)
    flashcards = []
    used_terms = set()

    for term in key_terms:
        if len(flashcards) >= count:
            break
        if term in used_terms:
            continue
        # find a sentence that mentions the term to use as the definition
        match = next((s for s in sentences if re.search(r"\b" + re.escape(term) + r"\b", s, re.IGNORECASE)), None)
        back = match if match else f"{term.capitalize()} is a key concept covered in {subject}."
        flashcards.append({
            "front": f"What is {term.capitalize()}?",
            "back": back[:400],
        })
        used_terms.add(term)

    # pad out with generic recall cards from remaining sentences if needed
    i = 0
    while len(flashcards) < count and i < len(sentences):
        s = sentences[i]
        i += 1
        if len(s) < 30:
            continue
        flashcards.append({
            "front": f"Explain the following concept from {subject}:",
            "back": s[:400],
        })
    return flashcards[:count]
