"""AI generation layer.

If `OPENAI_API_KEY` is configured, quizzes/flashcards are generated by calling
the OpenAI Chat Completions API with a strict JSON-output prompt.

If no key is configured, a deterministic, fully-offline heuristic generator
is used instead so the whole product still works end-to-end (useful for
local dev, demos, and grading environments without external API access).
"""
import json
import random
import re
from typing import List, Dict

import httpx

from app.config import settings
from app.services.pdf_service import split_into_sentences, identify_key_terms

random.seed()


# ===========================================================================
# Public entry points
# ===========================================================================
def generate_quiz(text: str, subject: str, question_count: int, difficulty: str,
                   question_types: List[str]) -> List[Dict]:
    if settings.OPENAI_API_KEY:
        try:
            return _generate_quiz_openai(text, subject, question_count, difficulty, question_types)
        except Exception as e:
            import logging
            logging.exception("OpenAI quiz generation failed, falling back to offline generator")
    return _generate_quiz_offline(text, subject, question_count, difficulty, question_types)

def generate_flashcards(text: str, subject: str, count: int) -> List[Dict]:
    
    if settings.OPENAI_API_KEY:
        try:
            return _generate_flashcards_openai(text, subject, count)
        except Exception as e:
            import logging
            logging.exception("OpenAI flashcard generation failed, falling back to offline generator")
    return _generate_flashcards_offline(text, subject, count)

# ===========================================================================
# OpenAI-backed generation
# ===========================================================================
_QUIZ_SYSTEM_PROMPT = """You are an expert curriculum writer for first-year BSCS/BSIT college students.
Generate quiz questions strictly as JSON. Do not include any commentary outside the JSON."""

_FLASHCARD_SYSTEM_PROMPT = """You are an expert study-guide writer for first-year BSCS/BSIT college students.
Generate flashcards strictly as JSON. Do not include any commentary outside the JSON."""


def _call_openai(system_prompt: str, user_prompt: str) -> str:
    resp = httpx.post(
        f"{settings.OPENAI_BASE_URL}/chat/completions",
        headers={"Authorization": f"Bearer {settings.OPENAI_API_KEY}", "Content-Type": "application/json"},
        json={
            "model": settings.OPENAI_MODEL,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "temperature": 0.4,
            "response_format": {"type": "json_object"},
        },
        timeout=60,
    )
    resp.raise_for_status()
    data = resp.json()
    return data["choices"][0]["message"]["content"]


def _generate_quiz_openai(text: str, subject: str, question_count: int, difficulty: str,
                           question_types: List[str]) -> List[Dict]:
    excerpt = text[:12000]  # keep prompt bounded
    user_prompt = f"""
Subject: {subject}
Difficulty: {difficulty}
Allowed question types: {', '.join(question_types)}
Number of questions: {question_count}

Source module text:
\"\"\"{excerpt}\"\"\"

Return JSON of the form:
{{"questions": [
  {{"question_type": "Multiple Choice", "question_text": "...", "choices": ["...","...","...","..."], "correct_answer": "..."}},
  {{"question_type": "True or False", "question_text": "...", "choices": ["True","False"], "correct_answer": "True"}},
  {{"question_type": "Identification", "question_text": "...", "choices": null, "correct_answer": "..."}}
]}}
Base every question on the source text. correct_answer must exactly match one of the choices (or be the identification answer).
"""
    content = _call_openai(_QUIZ_SYSTEM_PROMPT, user_prompt)
    parsed = json.loads(content)
    questions = parsed["questions"][:question_count]
    return questions


def _generate_flashcards_openai(text: str, subject: str, count: int) -> List[Dict]:
    excerpt = text[:12000]
    user_prompt = f"""
Subject: {subject}
Number of flashcards: {count}

Source module text:
\"\"\"{excerpt}\"\"\"

Return JSON of the form:
{{"flashcards": [{{"front": "A short question or term", "back": "A clear definition/explanation"}}]}}
Base every flashcard on the source text, one key concept per card.
"""
    content = _call_openai(_FLASHCARD_SYSTEM_PROMPT, user_prompt)
    parsed = json.loads(content)
    return parsed["flashcards"][:count]


# ===========================================================================
# Offline heuristic fallback (no external API required)
# ===========================================================================
_DIFFICULTY_SENTENCE_LEN = {
    "Easy": (25, 90),
    "Medium": (40, 140),
    "Hard": (60, 220),
    "Mixed": (25, 220),
}


def _pick_sentences(text: str, difficulty: str, n: int) -> List[str]:
    sentences = split_into_sentences(text)
    lo, hi = _DIFFICULTY_SENTENCE_LEN.get(difficulty, (25, 200))
    filtered = [s for s in sentences if lo <= len(s) <= hi]
    pool = filtered if len(filtered) >= n else sentences
    if not pool:
        pool = ["This module covers foundational concepts for the course."]
    random.shuffle(pool)
    # cycle through if not enough unique sentences
    out = []
    i = 0
    while len(out) < n:
        out.append(pool[i % len(pool)])
        i += 1
    return out


def _keyword_from_sentence(sentence: str, key_terms: List[str]) -> str:
    for term in key_terms:
        if re.search(r"\b" + re.escape(term) + r"\b", sentence, re.IGNORECASE):
            return term
    words = [w for w in re.findall(r"[A-Za-z]{5,}", sentence)]
    return words[0].lower() if words else "concept"


def _generate_quiz_offline(text: str, subject: str, question_count: int, difficulty: str,
                            question_types: List[str]) -> List[Dict]:
    key_terms = identify_key_terms(text) or [subject]
    sentences = _pick_sentences(text, difficulty, question_count)
    questions = []
    types_cycle = question_types if question_types else ["Multiple Choice"]

    for i in range(question_count):
        sentence = sentences[i]
        term = _keyword_from_sentence(sentence, key_terms)
        qtype = types_cycle[i % len(types_cycle)]

        if qtype == "True or False":
            is_true = random.random() > 0.5
            statement = sentence if is_true else _negate(sentence)
            questions.append({
                "question_type": "True or False",
                "question_text": f"True or False: {statement}",
                "choices": ["True", "False"],
                "correct_answer": "True" if is_true else "False",
            })
        elif qtype == "Identification":
            questions.append({
                "question_type": "Identification",
                "question_text": f"Based on the module, what key term relates to: \"{_blank_out(sentence, term)}\"?",
                "choices": None,
                "correct_answer": term,
            })
        else:  # Multiple Choice
            distractors = [t for t in key_terms if t != term][:3]
            while len(distractors) < 3:
                distractors.append(f"{term}-related concept {len(distractors)+1}")
            choices = distractors + [term]
            random.shuffle(choices)
            questions.append({
                "question_type": "Multiple Choice",
                "question_text": f"Which term best completes this statement from the module?\n\"{_blank_out(sentence, term)}\"",
                "choices": choices,
                "correct_answer": term,
            })
    return questions


def _blank_out(sentence: str, term: str) -> str:
    pattern = re.compile(re.escape(term), re.IGNORECASE)
    blanked = pattern.sub("____", sentence, count=1)
    if blanked == sentence:
        blanked = sentence + " (____)"
    return blanked[:280]


def _negate(sentence: str) -> str:
    replacements = [
        (r"\bis\b", "is not"), (r"\bare\b", "are not"),
        (r"\bcan\b", "cannot"), (r"\bwill\b", "will not"),
        (r"\bdoes\b", "does not"), (r"\bhas\b", "does not have"),
    ]
    for pattern, repl in replacements:
        if re.search(pattern, sentence, re.IGNORECASE):
            return re.sub(pattern, repl, sentence, count=1, flags=re.IGNORECASE)
    return "It is not true that " + sentence[0].lower() + sentence[1:]


def _generate_flashcards_offline(text: str, subject: str, count: int) -> List[Dict]:
    key_terms = identify_key_terms(text, max_terms=count * 2) or [subject]
    sentences = split_into_sentences(text)
    flashcards = []
    used_terms = set()

    for term in key_terms:
        if len(flashcards) >= count:
            break
        if term in used_terms:
            continue
        # find a sentence that mentions the term to use as the definition
        match = next((s for s in sentences if re.search(r"\b" + re.escape(term) + r"\b", s, re.IGNORECASE)), None)
        back = match if match else f"{term.capitalize()} is a key concept covered in {subject}."
        flashcards.append({
            "front": f"What is {term.capitalize()}?",
            "back": back[:400],
        })
        used_terms.add(term)

    # pad out with generic recall cards from remaining sentences if needed
    i = 0
    while len(flashcards) < count and i < len(sentences):
        s = sentences[i]
        i += 1
        if len(s) < 30:
            continue
        flashcards.append({
            "front": f"Explain the following concept from {subject}:",
            "back": s[:400],
        })
    return flashcards[:count]
